services:
  auth-service-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=auth-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '32769:5432'

  resources-service-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resource-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '32768:5432'
